version: "3"

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ".:/server"
    networks:
      - webnet
    # command: "./server:0.0.1"

  prometheus:
    build: .
    volumes:
      - "./prometheus.yml:/etc/prometheus/prometheus.yml"
    image: prom/prometheus:v2.40.7
    depends_on:
      - server

  graphana:
    build: .
    volumes:
      - "./grafana/config.ini:/etc/grafana/grafana.ini"
      - "./grafana/datasource.yml:/etc/grafana/provisioning/datasources/default.yaml"
      - "./grafana/dashboard.yml:/etc/grafana/provisioning/dashboards/default.yaml"
      - "./grafana/dashboards:/var/lib/grafana/dashboards"
    ports:
      - "3000:3000"
    image: grafana/grafana:9.4.2
    depends_on:
      - server

networks:
  webnet:
